# Generated by Django 5.0 on 2023-12-21 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_notes_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notes',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
