# Generated by Django 5.0 on 2023-12-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_notes_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='created_at',
        ),
    ]
