# Generated by Django 5.0 on 2023-12-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0007_alter_homework_options_alter_notes_options_todo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
