# Generated by Django 4.2.9 on 2024-01-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0008_alter_todo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todo'},
        ),
    ]
