# Generated by Django 4.2.9 on 2024-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0011_booksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='DefaultCity', max_length=50),
        ),
    ]
