# Generated by Django 4.2.9 on 2024-01-29 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardapp', '0014_alter_student_city_filmstarinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maintowns', models.CharField(max_length=100)),
                ('mainmalls', models.CharField(max_length=100)),
                ('Totalpop', models.IntegerField()),
                ('famous', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
                'db_table': 'city',
            },
        ),
    ]
