# Generated by Django 4.2.9 on 2024-01-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0015_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Totalpop',
            new_name='Total_pop',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='mainmalls',
            new_name='main_malls',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='maintowns',
            new_name='main_towns',
        ),
    ]
