# Generated by Django 4.2.9 on 2024-01-29 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardapp', '0016_rename_totalpop_city_total_pop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techtools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('where_using', models.CharField(max_length=100)),
                ('how_many_users', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'techtools',
                'verbose_name_plural': 'techtools',
                'db_table': 'techtools',
            },
        ),
    ]
